name: Integração Continua

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Inicia banco
        working-directory: 3983-integracao-continua-projeto_inicial
        run: docker compose up -d postgres

      - name: Lint
        working-directory: 3983-integracao-continua-projeto_inicial
        run: docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint golangci-lint run controllers/ database/ models/ routes/

      - name: Test
        working-directory: 3983-integracao-continua-projeto_inicial
        run: docker compose up -d app && docker compose exec -T app go test -v ./...

